### ISSUE TITLE
XBT currency conversion issues

### ISSUE THREAD

**Issue by joequant** [joequant/bitquant#4]
The currency convesion rate does not take into account bid-ask spread, and does not take into account the hidden fee for ANX.

**Comment by henryyu731** [comment]
Shall we have a call tomm to go through these comments?

**Comment by henryyu731** [comment]
It's not that urgent.  I just wanted to have the bugs in the smart contract
recorded somewhere so that we can deal with them later.  I don't think that
any of these issues require any action for current pending contracts.  It's
just that if anyone did a copy and paste, I wanted to have the gotchas
publicly recorded for future reference.

**Comment by henryyu731** [comment]
Joe

OK, I take it to mean that nothing in the Airbutton Contract that needs to
be amended at this stage. Do you intend to sign it soon?

*Henry Yu*
Co-Founder


*Your Own Terms*
www.crypto-law.com

**Comment by joequant** [comment]
This problem is not urgent, and it is not necessary to take any action at this time.  The two specific concerns are that:

1) the bid-ask spread and fees could be significant for any large transaction
2) in large transactions it would be easy to push the price of the HK exchanges
